# Server configurations (if needed)
server:
  port: 8080

# Logging configurations (if needed)
logging:
  level:
    root: INFO

spring:
  application:
    name: MediLab Solutions Gateway Service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - POST
              - GET
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: backend-route
          uri: ${BACKEND_ROUTE:http://localhost:8081}
          predicates:
            - Path=/patients/**, /auth/**
          metadata:
            cors:
              allowedOrigins:
                - "http://localhost:4200"
              allowedHeaders:
                - "*"
              allowedMethods:
                - "*"
        - id: notes-route
          uri: ${NOTES_ROUTE:http://localhost:8082}
          predicates:
            - Path=/notes/**
          metadata:
            cors:
              allowedOrigins:
                - "http://localhost:4200"
              allowedHeaders:
                - "*"
              allowedMethods:
                - "*"
        - id: risque-route
          uri: ${RISQUE_ROUTE:http://localhost:8083}
          predicates:
            - Path=/risque/**
          metadata:
            cors:
              allowedOrigins:
                - "http://localhost:4200"
              allowedHeaders:
                - "*"
              allowedMethods:
                - "*"

routes:
  backend: ${BACKEND_ROUTE:http://localhost:8081}
  notes: ${NOTES_ROUTE:http://localhost:8082}
  risque: ${RISQUE_ROUTE:http://localhost:8083}

