server:
  port: 8083


spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

cors:
  enabled: true
  allowedAddress: ${ALLOWED_ADDRESS:http://localhost:4200,http://localhost:8080,http://localhost:8083}

